# Generated by Django 6.0.3 on 2026-04-05 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_alter_article_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='lu',
            field=models.BooleanField(default=False),
        ),
    ]
