# Generated by Django 6.0.3 on 2026-04-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_commentaire_lu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
